### ISSUE TITLE
Mahalanobis Distance: Turbulence Calculation Function

### ISSUE THREAD

**Issue by emjay032** [tzhangwps/Turbulence-and-Systemic-Risk#6]
Hello,

If you compare the Mahalanobis distance with the turbulence index, the turbulence index is a slight modification of the Mahalanobis distance (see Kritzman & Li, 2010).

Turbulence is the squared Mahalanobis Distance so i think in your function for calculating the Turbulence via scipy.spatial.distance.mahalanobis you need to square the distance in order to get the turbulence index (see documentation scipy)
right now you calculated the Mahalanobis distance:

mahalanobis_distance = distance.mahalanobis(u=current_data.iloc[:, 1:],
                                                                v=historical_sample_means,
                                                                VI=inverse_covariance_matrix)

But it should rather be:

mahalanobis_distance = distance.mahalanobis(u=current_data.iloc[:, 1:],
                                                                v=historical_sample_means,
                                                                VI=inverse_covariance_matrix)

turbulence = mahalanobis_distance **2

Or calculate it using numpy:

y_t = current_data.iloc[:,1:]
mu = historical_sample_means 

Turbulence = np.dot(np.dot((y_t-mu),inverse_covariance_matrix), ((y_t-mu).transpose()))

But amazing work from you!

**Comment by tzhangwps** [comment]
@emjay032 Thanks! I agree with your suggested change, and have implemented it in /src/calculate.py
